name: couponsgate
description:  couponsgate app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  shared_preferences: ^0.5.12+4
  clipboard_manager: ^0.0.1
  convex_bottom_bar: ^2.6.0
  giffy_dialog: ^1.8.0
  dotted_border: ^1.0.7
  getwidget: ^1.1.0
  responsive_grid: ^1.2.1+1
  url_launcher: ^5.7.10
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.6
  flutter_html: ^1.1.1
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.2
  flutter_launcher_icons: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/alert.png
    - assets/images/logo.png
    - assets/images/success.png
    - lib/languages/en.json
    - lib/languages/ar.json
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/hacentunisia.ttf
    - family:  MyIcons
      fonts:
        - asset: assets/MyIcons.ttf